In [1]:
import fastf1
fastf1.Cache.enable_cache("../data/cache")

In [5]:
session = fastf1.get_session(
    2026,
    "Monaco",
    "R"
)

In [6]:
session.load()

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '10', '6', '81', '30', '41', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3']

In [7]:
session
type(session)

fastf1.core.Session

In [8]:
dir(session)

['_QUALI_LIKE_SESSIONS',
 '_RACE_LIKE_SESSIONS',
 '_Session__fix_tyre_info',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_first_lap_time_from_ergast',
 '_add_track_status_to_laps',
 '_calculate_quali_like_session_results',
 '_calculate_race_like_session_results',
 '_calculate_t0_date',
 '_car_data',
 '_check_lap_accuracy',
 '_drivers_from_f1_api',
 '_drivers_results_from_ergast',
 '_ergast',
 '_fix_missing_laps_retired_on_track',
 '_get_property_warn_not_loaded',
 '_laps',
 '_load_drivers_results',
 '_load_laps_data',
 '_load_race_control_messages',
 '_load_session_info',
 '_load_session_status_data',
 '_load_telemetry',
 '_load_total_lap_count',
 '_load_track_status_data',
 '_load_weather_data',
 '_pos_data',
 '_race_control_messages',
 '_results',
 '_session_info',
 '_session_split_times',
 '_session_start_time',
 '_session_status',
 '_set_laps_deleted_from_rcm',
 '_t0_date',
 '_total_laps',
 '_track_status',
 '_weather_data',
 'api_path',
 'car_data',
 'date',
 'drivers',
 'event',
 'f1_api_support',
 'get_circuit_info',
 'get_driver',
 'laps',
 'load',
 'name',
 'pos_data',
 'race_control_messages',
 'results',
 'session_info',
 'session_start_time',
 'session_status',
 't0_date',
 'total_laps',
 'track_status',
 'weather_data']

In [10]:
session.results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,1,1.0,NaT,NaT,NaT,0 days 02:23:31.243000,Finished,25.0,78.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,2.0,2,3.0,NaT,NaT,NaT,0 days 00:00:06.271000,Finished,18.0,78.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,3.0,3,9.0,NaT,NaT,NaT,0 days 00:00:20.369000,Finished,15.0,78.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,4.0,4,5.0,NaT,NaT,NaT,0 days 00:00:23.394000,Finished,12.0,78.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,5,7.0,NaT,NaT,NaT,0 days 00:00:24.261000,Finished,10.0,78.0

In [11]:
session.laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:56:50.495000,NOR,1,0 days 00:01:30.629000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:39.379000,...,True,McLaren,0 days 00:55:19.645000,2026-06-07 13:03:11.904,12,8.0,False,,False,False
1,0 days 00:58:11.179000,NOR,1,0 days 00:01:20.684000,2.0,1.0,NaT,NaT,0 days 00:00:21.738000,0 days 00:00:37.534000,...,True,McLaren,0 days 00:56:50.495000,2026-06-07 13:04:42.754,1,8.0,False,,False,True
2,0 days 00:59:31.374000,NOR,1,0 days 00:01:20.195000,3.0,1.0,NaT,NaT,0 days 00:00:21.482000,0 days 00:00:37.614000,...,True,McLaren,0 days 00:58:11.179000,2026-06-07 13:06:03.438,1,8.0,False,,False,True
3,0 days 01:00:50.865000,NOR,1,0 days 00:01:19.491000,4.0,1.0,NaT,NaT,0 days 00:00:21.206000,0 days 00:00:37.169000,...,True,McLaren,0 days 00:59:31.374000,2026-06-07 13:07:23.633,1,8.0,False,,False,True
4,0 days 01:02:09.853000,NOR,1,0 days 00:01:18.988000,5.0,1.0,NaT,NaT,0 days 00:00:20.871000,0 days 00:00:36.960000,...,True,McLaren,0 days 01:00:50.865000,2026-06-07 13:08:43.124,1,8.0,False,,False,True

In [12]:
session.weather_data.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:24.792000,23.3,64.7,1022.1,False,33.1,244,0.5
1,0 days 00:01:24.809000,23.4,64.1,1022.0,False,34.0,0,0.0
2,0 days 00:02:24.794000,23.0,64.1,1022.0,False,34.0,0,0.0
3,0 days 00:03:24.789000,23.3,63.5,1022.1,False,34.4,0,0.0
4,0 days 00:04:24.791000,23.5,63.7,1022.1,False,35.1,131,0.5

In [13]:
session.track_status.head()

                    Time Status   Message
0        0 days 00:00:00      1  AllClear
1 0 days 00:00:36.058000      2    Yellow
2 0 days 00:05:49.640000      1  AllClear
3 0 days 00:17:32.354000      2    Yellow
4 0 days 00:18:11.662000      1  AllClear

In [14]:
session.race_control_messages.head()

,Time,Category,Message,Status,Flag,Scope,Sector,RacingNumber,Lap
0,2026-06-07 12:20:01,Flag,GREEN LIGHT - PIT EXIT OPEN,None,GREEN,Track,NaN,None,1
1,2026-06-07 12:22:10,Other,INCIDENT INVOLVING CAR 11 (PER) NOTED - FAILIN...,None,None,None,NaN,None,1
2,2026-06-07 12:25:25,Flag,YELLOW IN TRACK SECTOR 18,None,YELLOW,Sector,18.0,None,1
3,2026-06-07 12:26:04,Flag,CLEAR IN TRACK SECTOR 18,None,CLEAR,Sector,18.0,None,1
4,2026-06-07 12:30:01,Other,PIT EXIT CLOSED,None,None,None,NaN,None,1

In [ ]:
lap = session.laps.pick_fastest()
lap.get_car_data()

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2026-06-07 15:23:00.672,11679.0,263.0,6,100.0,False,0,car,0 days 00:00:00.054000,0 days 03:15:08.413000
1,2026-06-07 15:23:00.872,11824.0,265.0,6,100.0,False,0,car,0 days 00:00:00.254000,0 days 03:15:08.613000
2,2026-06-07 15:23:01.072,11905.0,267.0,6,100.0,False,0,car,0 days 00:00:00.454000,0 days 03:15:08.813000
3,2026-06-07 15:23:01.232,11870.0,267.0,6,100.0,False,0,car,0 days 00:00:00.614000,0 days 03:15:08.973000
4,2026-06-07 15:23:01.392,11911.0,268.0,6,100.0,False,0,car,0 days 00:00:00.774000,0 days 03:15:09.133000
...,...,...,...,...,...,...,...,...,...,...
269,2026-06-07 15:24:12.832,11144.0,252.0,6,100.0,False,0,car,0 days 00:01:12.214000,0 days 03:16:20.573000
270,2026-06-07 15:24:13.032,11292.0,254.0,6,100.0,False,0,car,0 days 00:01:12.414000,0 days 03:16:20.773000
271,2026-06-07 15:24:13.312,11395.0,256.0,6,100.0,False,0,car,0 days 00:01:12.694000,0 days 03:16:21.053000
272,2026-06-07 15:24:13.592,11539.0,260.0,6,100.0,False,0,car,0 days 00:01:12.974000,0 days 03:16:21.333000
273,2026-06-07 15:24:13.832,11609.0,262.0,6,100.0,False,0,car,0 days 00:01:13.214000,0 days 03:16:21.573000

In [16]:
lap.get_pos_data

<bound method Lap.get_pos_data of Time                      0 days 03:16:21.840000
Driver                                       ANT
DriverNumber                                  12
LapTime                   0 days 00:01:13.481000
LapNumber                                   76.0
Stint                                        5.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:19.379000
Sector2Time               0 days 00:00:34.566000
Sector3Time               0 days 00:00:19.536000
Sector1SessionTime        0 days 03:15:27.768000
Sector2SessionTime        0 days 03:16:02.334000
Sector3SessionTime        0 days 03:16:21.870000
SpeedI1                                    213.0
SpeedI2                                    199.0
SpeedFL                                    258.0
SpeedST                                    271.0
IsPersonalBest                              True
Compound                                    SOFT
TyreLife                                    12.0
FreshTyre                                  False
Team                                    Mercedes
LapStartTime              0 days 03:15:08.359000
LapStartDate          2026-06-07 15:23:00.618000
TrackStatus                                    1
Position                                     1.0
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 275, dtype: object>

In [17]:
lap.get_telemetry()

KeyError: "None of ['Date'] are in the columns"

In [18]:
print(fastf1.__version__)

3.8.3

In [19]:
car_data = lap.get_car_data()

car_data.columns

Index(['Date', 'RPM', 'Speed', 'nGear', 'Throttle', 'Brake', 'DRS', 'Source',
       'Time', 'SessionTime'],
      dtype='object')

In [21]:
pos_data = lap.get_pos_data()

pos_data.columns

RangeIndex(start=0, stop=0, step=1)

In [22]:
car_data.head()

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2026-06-07 15:23:00.672,11679.0,263.0,6,100.0,False,0,car,0 days 00:00:00.054000,0 days 03:15:08.413000
1,2026-06-07 15:23:00.872,11824.0,265.0,6,100.0,False,0,car,0 days 00:00:00.254000,0 days 03:15:08.613000
2,2026-06-07 15:23:01.072,11905.0,267.0,6,100.0,False,0,car,0 days 00:00:00.454000,0 days 03:15:08.813000
3,2026-06-07 15:23:01.232,11870.0,267.0,6,100.0,False,0,car,0 days 00:00:00.614000,0 days 03:15:08.973000
4,2026-06-07 15:23:01.392,11911.0,268.0,6,100.0,False,0,car,0 days 00:00:00.774000,0 days 03:15:09.133000

In [24]:
print(pos_data.shape)

(0, 0)

In [28]:
print(lap['Driver'])
print(lap['LapNumber'])

ANT
76.0

In [29]:
lap2 = session.laps.iloc[100]

print(lap2['Driver'])
print(lap2['LapNumber'])

pos = lap2.get_pos_data()

print(pos.shape)

GAS
57.0
(0, 0)

In [30]:
session.event

RoundNumber                                                          6
Country                                                         Monaco
Location                                                   Monte Carlo
OfficialEventName    FORMULA 1 LOUIS VUITTON GRAND PRIX DE MONACO 2026
EventDate                                          2026-06-07 00:00:00
EventName                                            Monaco Grand Prix
EventFormat                                               conventional
Session1                                                    Practice 1
Session1Date                                 2026-06-05 13:30:00+02:00
Session1DateUtc                                    2026-06-05 11:30:00
Session2                                                    Practice 2
Session2Date                                 2026-06-05 17:00:00+02:00
Session2DateUtc                                    2026-06-05 15:00:00
Session3                                                    Practice 3
Session3Date                                 2026-06-06 12:30:00+02:00
Session3DateUtc                                    2026-06-06 10:30:00
Session4                                                    Qualifying
Session4Date                                 2026-06-06 16:00:00+02:00
Session4DateUtc                                    2026-06-06 14:00:00
Session5                                                          Race
Session5Date                                 2026-06-07 15:00:00+02:00
Session5DateUtc                                    2026-06-07 13:00:00
F1ApiSupport                                                      True
Name: 7, dtype: object

In [31]:
print(session.car_data.keys())

dict_keys(['12', '44', '10', '6', '81', '30', '41', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3'])

In [32]:
print(session.pos_data.keys())

dict_keys(['12', '44', '10', '6', '81', '30', '41', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3'])

In [33]:
lap = session.laps.pick_fastest()

print(lap['Driver'])
print(lap['LapNumber'])

pos_data = lap.get_pos_data()

print(pos_data.shape)

ANT
76.0
(0, 0)

In [34]:
driver = lap['DriverNumber']

print(session.pos_data[driver].head())
print(session.pos_data[driver].shape)

                     Date   Status    X    Y    Z Source  \
0 2026-06-07 12:08:38.424  OnTrack  0.0  0.0  0.0    pos
1 2026-06-07 12:08:38.644  OnTrack  0.0  0.0  0.0    pos
2 2026-06-07 12:08:38.844  OnTrack  0.0  0.0  0.0    pos
3 2026-06-07 12:08:39.024  OnTrack  0.0  0.0  0.0    pos
4 2026-06-07 12:08:39.184  OnTrack  0.0  0.0  0.0    pos

                    Time            SessionTime
0 0 days 00:00:46.165000 0 days 00:00:46.165000
1 0 days 00:00:46.385000 0 days 00:00:46.385000
2 0 days 00:00:46.585000 0 days 00:00:46.585000
3 0 days 00:00:46.765000 0 days 00:00:46.765000
4 0 days 00:00:46.925000 0 days 00:00:46.925000
(8087, 8)

In [35]:
lap = session.laps.pick_fastest()

print("Driver:", lap["Driver"])
print("Lap Number:", lap["LapNumber"])
print("Lap Start:", lap["LapStartTime"])
print("Lap Time:", lap["LapTime"])

pos = lap.get_pos_data()

print(pos.shape)
print(pos.head())

Driver: ANT
Lap Number: 76.0
Lap Start: 0 days 03:15:08.359000
Lap Time: 0 days 00:01:13.481000
(0, 0)
Empty DataFrame
Columns: []
Index: []